server:
  port: 8081

spring:
  application:
    name: flight-search-service
  data:
    mongodb:
      uri: mongodb+srv://root:uM5ZxGuvOqZD0gbX@flight-search.ywcubz4.mongodb.net/flight-search?retryWrites=true&w=majority



